version: '3'  # Define the version of Docker Compose

services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"  # Map port 5252 of the container to port 5252 on the host
    depends_on:
      - front-end  # Ensure back-end service waits for the front-end to start

  front-end:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: softy-pinko-front-end:task4
    ports:
      - "80:80"  # Map port 80 of the container to port 80 on the host
