version: '3'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end-1
      - back-end-2

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - back-end-1
      - back-end-2

  back-end-1:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end-1

  back-end-2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end-2
